//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataDumper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GameData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataDumper.GameData", typeof(GameData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_ArchetypeDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_ArchetypeDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_BigPickupDistributionDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_BigPickupDistributionDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_ChainedPuzzleDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_ChainedPuzzleDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_ChainedPuzzleTypeDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_ChainedPuzzleTypeDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_CommodityDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_CommodityDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_ComplexResourceSetDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_ComplexResourceSetDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_ConsumableDistributionDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_ConsumableDistributionDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_CustomAssetShardDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_CustomAssetShardDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_EnemyBalancingDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_EnemyBalancingDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_EnemyBehaviorDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_EnemyBehaviorDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_EnemyDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_EnemyDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_EnemyDetectionDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_EnemyDetectionDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_EnemyGroupDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_EnemyGroupDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_EnemyMovementDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_EnemyMovementDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_EnemyPopulationDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_EnemyPopulationDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_EnemySFXDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_EnemySFXDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_EnvironmentFeedbackDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_EnvironmentFeedbackDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_EventSequenceActionDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_EventSequenceActionDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_EventSequenceDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_EventSequenceDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_ExpeditionBalanceDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_ExpeditionBalanceDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_ExtractionEventDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_ExtractionEventDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_FeedbackDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_FeedbackDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_FlashlightSettingsDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_FlashlightSettingsDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_FogSettingsDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_FogSettingsDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_GameSetupDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_GameSetupDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_GearCategoryDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_GearCategoryDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_GearCategoryFilterDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_GearCategoryFilterDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_GearDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_GearDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_GearDecalDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_GearDecalDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_GearFlashlightPartDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_GearFlashlightPartDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_GearFrontPartDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_GearFrontPartDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_GearMagPartDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_GearMagPartDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_GearMeleeHandlePartDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_GearMeleeHandlePartDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_GearMeleeHeadPartDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_GearMeleeHeadPartDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_GearMeleeNeckPartDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_GearMeleeNeckPartDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_GearMeleePommelPartDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_GearMeleePommelPartDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_GearPaletteDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_GearPaletteDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_GearPartAttachmentDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_GearPartAttachmentDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_GearPatternDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_GearPatternDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_GearPerkDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_GearPerkDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_GearReceiverPartDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_GearReceiverPartDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_GearSightPartDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_GearSightPartDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_GearStockPartDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_GearStockPartDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_GearToolDeliveryPartDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_GearToolDeliveryPartDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_GearToolGripPartDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_GearToolGripPartDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_GearToolMainPartDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_GearToolMainPartDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_GearToolPayloadPartDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_GearToolPayloadPartDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_GearToolScreenPartDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_GearToolScreenPartDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_GearToolTargetingPartDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_GearToolTargetingPartDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_ItemDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_ItemDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_ItemFPSSettingsDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_ItemFPSSettingsDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_ItemPartDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_ItemPartDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_LevelGenSettingsDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_LevelGenSettingsDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_LevelLayoutDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_LevelLayoutDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_LightSettingsDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_LightSettingsDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_LootDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_LootDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_MarkerGroupDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_MarkerGroupDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_MiningMarkerDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_MiningMarkerDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_MusicStateDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_MusicStateDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_PlayerDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_PlayerDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_PlayerDialogDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_PlayerDialogDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_PlayerOfflineGearDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_PlayerOfflineGearDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_RecoilDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_RecoilDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_RundownDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_RundownDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_ServiceMarkerDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_ServiceMarkerDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_StaticSpawnDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_StaticSpawnDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_SurvivalWavePopulationDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_SurvivalWavePopulationDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_SurvivalWaveSettingsDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_SurvivalWaveSettingsDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_TechMarkerDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_TechMarkerDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_WardenObjectiveDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_WardenObjectiveDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_WeaponAudioDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_WeaponAudioDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_WeaponDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_WeaponDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_WeaponMuzzleFlashDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_WeaponMuzzleFlashDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GameData_WeaponShellCasingDataBlock_bin {
            get {
                object obj = ResourceManager.GetObject("GameData_WeaponShellCasingDataBlock_bin", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
